"""Controller-owned hardware ports.

These structural protocols are the only hardware capabilities application
services may depend on. Concrete USB, Modbus and local GPIO adapters remain in
the infrastructure modules and are constructed only by the Controller.
"""

from __future__ import annotations

from typing import Any, Callable, Protocol, runtime_checkable


@runtime_checkable
class ClockPort(Protocol):
    def monotonic(self) -> float: ...

    def sleep(self, seconds: float) -> None: ...


@runtime_checkable
class NucleoTransportPort(Protocol):
    @property
    def communication_ok(self) -> bool: ...

    @property
    def is_armed(self) -> bool: ...

    @property
    def max_move_steps(self) -> int: ...

    def start(self) -> None: ...

    def close(self) -> None: ...

    def arm(self, safety_permissive: bool = True) -> bool: ...

    def disarm(self) -> bool: ...

    def stop(self) -> bool: ...

    def reset_connection(self) -> dict[str, Any]: ...

    def move(
        self,
        axis: str,
        direction: int,
        steps: int,
        speed_hz: float,
        timeout_s: float | None = None,
        stop_requested: Callable[[], bool] | None = None,
    ) -> dict[str, Any]: ...

    def home_parallel(self, plans: dict[str, dict[str, Any]]) -> dict[str, int]: ...

    def move_parallel(
        self,
        plans: dict[str, dict[str, Any]],
        *,
        timeout_s: float,
        stop_requested: Callable[[], bool] | None = None,
    ) -> dict[str, Any]: ...

    def alarm_channel(self) -> dict[str, Any]: ...

    def status_payload(self) -> dict[str, Any]: ...


@runtime_checkable
class IRIVIOPort(Protocol):
    @property
    def communication_ok(self) -> bool: ...

    def start(self) -> None: ...

    def close(self) -> None: ...

    def input_active(self, name: str) -> bool: ...

    def input_device(self, name: str) -> Any: ...

    def output_device(self, name: str) -> Any: ...

    def output_value(self, name: str) -> bool: ...

    def set_output(self, name: str, value: bool) -> None: ...

    def pulse_output(
        self,
        name: str,
        duration_s: float,
        stop_requested: Callable[[], bool] | None = None,
    ) -> None: ...

    def alarm_channels(self) -> list[dict[str, Any]]: ...

    def status_payload(self) -> dict[str, Any]: ...


@runtime_checkable
class PiControlIOPort(Protocol):
    @property
    def communication_ok(self) -> bool: ...

    def start(self) -> None: ...

    def close(self) -> None: ...

    def input_active(self, name: str) -> bool: ...

    def set_output(self, name: str, active: bool) -> None: ...

    def output_active(self, name: str) -> bool: ...

    def alarm_channels(self) -> list[dict[str, Any]]: ...

    def position_channels(self) -> list[dict[str, Any]]: ...

    def status_payload(self) -> dict[str, Any]: ...
